---
language: python

env:
  - IMAGE=ubuntu TAG=bionic
  - IMAGE=ubuntu TAG=xenial
  - IMAGE=ubuntu TAG=artful
  - IMAGE=debian TAG=jessie
  - IMAGE=debian TAG=stretch
  - IMAGE=centos TAG=7
  - IMAGE=fedora TAG=24
  - IMAGE=fedora TAG=27
  - IMAGE=amazonlinux TAG=1

dist: trusty
sudo: required

cache: pip

before_install:
  - docker version
  - docker pull $IMAGE:$TAG
  - docker run --name test -di $IMAGE:$TAG /bin/sh
  - if [ "$IMAGE" = "ubuntu" -o "$IMAGE" = "debian" ]; then
      docker exec test apt-get update;
      docker exec test apt-get install -y python ca-certificates;
    fi
  - if [ "$IMAGE" = "centos" -o "$IMAGE" = "fedora" ]; then
      docker exec test yum install -y python ca-certificates;
    fi

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' | tee ansible.cfg
  - pip install ansible-lint
  - ansible-lint --version

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - ansible-playbook -i test, tests/test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
