---

- name: import task for Debian derivatives
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: import task for RedHat derivatives
  import_tasks: redhat.yml
  when: ansible_distribution in ["CentOS", "Fedora"]
