---

- name: docker release key is registered
  rpm_key:
    key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present

- name: docker-ce yum repository is registered
  get_url:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  failed_when: ansible_distribution | lower not in ['centos', 'fedora']

- name: remove old versions by yum
  yum:
    name: "{{ packages }}"
    state: absent
  when: ansible_distribution != "Fedora"
  vars:
    packages:
      - docker
      - docker-common
      - docker-selinux
      - docker-engine

- name: remove old versions by dnf
  dnf:
    name: "{{ packages }}"
    state: absent
  when: ansible_distribution == "Fedora"
  vars:
    packages:
      - docker
      - docker-common
      - docker-selinux
      - docker-engine

- name: enable docker-ce-{{ docker_ce_channel }}
  ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: docker-ce-{{ docker_ce_channel }}
    option: enabled
    value: 1
  when: docker_ce_channel in ['edge', 'test']

- name: docker-ce is installed by yum
  yum:
    name: 'docker-ce-{{ docker_ce_version }}'
    state: present
  when: not ansible_check_mode and ansible_distribution != "Fedora"

- name: docker-ce is installed by dnf
  dnf:
    name: 'docker-ce-{{ docker_ce_version }}'
    state: present
  when: not ansible_check_mode and ansible_distribution == "Fedora"
